<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Element119\HyvaCanvas\ViewModel\Canvas;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Canvas $canvasViewModel */
$canvasViewModel = $viewModels->require(Canvas::class);
$canvasBlockName = $canvasViewModel->getCanvasBlockName($block);
?>
<div x-data="initCanvas_<?= $escaper->escapeHtmlAttr($canvasBlockName); ?>()"
     x-init="init()"
     @resize.window="setCanvasWidth()"
     class="flex flex-col mx-auto">
    <canvas id="canvas-<?= $escaper->escapeHtmlAttr($canvasBlockName); ?>"
            class="border-2 border-dashed rounded-2xl"
            height="350"
            :width="canvasWidth"
            @mousedown="onMouseDown($event)"
            @mousemove="onMouseMove($event)"
            @mouseup="onMouseUp()"
            @touchstart.passive="onTouchStart($event)"
            @touchmove.passive="onTouchMove($event)"
            @touchend.passive="onTouchEnd()">
        <?= $escaper->escapeHtml(__('Your drawing here...')); ?>
    </canvas>
    <div class="flex justify-between mt-4">
        <button id="canvas-submit-<?= $escaper->escapeHtmlAttr($canvasBlockName); ?>"
                class="btn btn-primary"
                @click="submitCanvas()">
            <?= $escaper->escapeHtml(__('Submit')); ?>
        </button>
        <button id="canvas-clear-<?= $escaper->escapeHtmlAttr($canvasBlockName); ?>"
                class="btn btn-default"
                @click="resetCanvas()">
            <?= $escaper->escapeHtml(__('Clear')); ?>
        </button>
    </div>
</div>
<script>
    function initCanvas_<?= $escaper->escapeJs($canvasBlockName); ?>()
    {
        return {
            buttons: {
                clear: null,
                submit: null,
            },
            canvas: null,
            canvasBlockName: '<?= $escaper->escapeJs($canvasBlockName); ?>',
            canvasContext: null,
            canvasImage: null,
            canvasImageDefault: null,
            canvasWidth: 400,
            currentMousePosition: {
                x: 0,
                y: 0,
            },
            isDrawing: false,
            previousMousePosition: this.currentMousePosition,

            init()
            {
                this.buttons.clear = document.getElementById('canvas-clear-' + this.canvasBlockName);
                this.buttons.submit = document.getElementById('canvas-submit-' + this.canvasBlockName);
                this.canvas = document.getElementById('canvas-' + this.canvasBlockName);
                this.canvasContext = this.canvas.getContext('2d');
                this.canvasImageDefault = this.canvas.toDataURL();

                this.setCanvasWidth();
                this.initExternalEventListeners();
                this.initDrawingLogic();
            },

            initDrawingLogic()
            {
                const self = this;

                window.requestCanvasAnimationFrame = (function(callback) {
                    return window.requestAnimationFrame || function(callback) {
                        window.setTimeout(callback, 1000 / 60);
                    };
                })();

                (function drawLoop() {
                    requestCanvasAnimationFrame(drawLoop);
                    self.renderCanvas();
                })();
            },

            initExternalEventListeners()
            {
                const self = this;

                [
                    'touchstart',
                    'touchend',
                    'touchmove',
                ].forEach((eventName) => {
                    document.body.addEventListener(
                        eventName,
                        (event) => {
                            if (event.target === self.canvas) {
                                event.preventDefault();
                            }
                        },
                        {
                            passive: false,
                        }
                    );
                });
            },

            getMousePosition(mouseEvent)
            {
                const rect = this.canvas.getBoundingClientRect();

                return {
                    x: mouseEvent.clientX - rect.left,
                    y: mouseEvent.clientY - rect.top,
                }
            },

            getTouchPosition(touchEvent)
            {
                const rect = this.canvas.getBoundingClientRect();

                return {
                    x: touchEvent.touches[0].clientX - rect.left,
                    y: touchEvent.touches[0].clientY - rect.top,
                }
            },

            onMouseDown(event)
            {
                this.isDrawing = true;
                this.previousMousePosition = this.getMousePosition(event);
            },

            onMouseMove(event)
            {
                this.currentMousePosition = this.getMousePosition(event);
            },

            onMouseUp()
            {
                this.isDrawing = false;
            },

            onTouchStart(event)
            {
                this.currentMousePosition = this.getTouchPosition(event);

                const touch = event.touches[0];
                const mouseEvent = new MouseEvent(
                    'mousedown',
                    {
                        clientX: touch.clientX,
                        clientY: touch.clientY,
                    }
                );

                this.canvas.dispatchEvent(mouseEvent);
            },

            onTouchMove(event)
            {
                const touch = event.touches[0];
                const mouseEvent = new MouseEvent(
                    'mousemove',
                    {
                        clientX: touch.clientX,
                        clientY: touch.clientY,
                    }
                );

                this.canvas.dispatchEvent(mouseEvent);
            },

            onTouchEnd()
            {
                this.canvas.dispatchEvent(new MouseEvent('mouseup', {}));
            },

            renderCanvas()
            {
                if (this.isDrawing) {
                    this.canvasContext.moveTo(this.previousMousePosition.x, this.previousMousePosition.y);
                    this.canvasContext.lineTo(this.currentMousePosition.x, this.currentMousePosition.y);
                    this.canvasContext.stroke();

                    this.previousMousePosition = this.currentMousePosition;
                }
            },

            resetCanvas()
            {
                this.canvas.width = this.canvas.width;
            },

            setCanvasWidth()
            {
                this.canvasWidth = window.matchMedia('(max-width: 768px)').matches ? 400 : 600;
                this.resetCanvas();
            },

            submitCanvas()
            {
                this.canvasImage = this.canvas.toDataURL();

                if (this.canvasImage !== this.canvasImageDefault) {
                    window.dispatchEvent(new CustomEvent(
                        'customer-canvas-submitted',
                        {
                            detail: {
                                canvasBlockName: this.canvasBlockName,
                                canvasImage: this.canvasImage,
                            },
                        }
                    ));
                }
            },
        };
    }
</script>
